openapi: 3.0.3
info:
  title: Project & Day API
  version: 1.0.0
  description: An OpenAPI specification for project management, day templates, tasks, forms, media, and related user progress tracking.
servers:
  - url: https://api.example.com

########################################################
# COMPONENTS
########################################################
components:
  ######################################################
  # HEADERS
  ######################################################
  headers:
    Set-JWT:
      schema:
        type: string
        description: JWT token
        example: "jwt=tokenValue; Path=/; HttpOnly; Secure"
    Clear-JWT:
      schema:
        type: string
        description: JWT token clear
        example: "jwt=; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Path=/;"
    HomeRedirect:
      schema:
        type: string
        description: Home redirect
        example: /
    LoginRedirect:
      schema:
        type: string
        description: Login redirect
        example: /auth/login

  ######################################################
  # SECURITY SCHEMES
  ######################################################
  securitySchemes:
    admin_jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
    user_jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT

  ######################################################
  # RESPONSES
  ######################################################
  responses:
    UnauthorizedLoginError:
      description: Unauthorized login
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    UnauthorizedError:
      description: Unauthorized access
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    AuthorizationSuccess:
      description: OK
      headers:
        Set-Cookie:
          $ref: "#/components/headers/Set-JWT"
        Location:
          $ref: "#/components/headers/HomeRedirect"
    UnauthorizationSuccess:
      description: OK
      headers:
        Set-Cookie:
          $ref: "#/components/headers/Clear-JWT"
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    NotAcceptable:
      description: Not Acceptable
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  ######################################################
  # PARAMETERS
  ######################################################
  parameters:
    limit:
      name: limit
      description: Limit of the list
      example: 10
      in: query
      required: true
      schema:
        type: integer

    offset:
      name: offset
      description: Offset of the list
      example: 0
      in: query
      required: true
      schema:
        type: integer

    sortOrder:
      name: sortOrder
      in: query
      description: "Order or position (general integer query usage)"
      required: true
      schema:
        $ref: "#/components/schemas/sortOrder"

    fieldUUIDQuery:
      name: field_uuid
      in: query
      description: "Form field UUID in the query"
      required: true
      schema:
        $ref: "#/components/schemas/fieldUUID"

    componentUUID:
      name: component_uuid
      in: path
      description: "Component UUID in the path"
      required: true
      schema:
        $ref: "#/components/schemas/componentUUID"

    projectBlueprintUUID:
      name: project_blueprint_uuid
      in: path
      required: true
      description: "The UUID of the project blueprint"
      schema:
        $ref: "#/components/schemas/projectBlueprintUUID"

    dayBlueprintUUID:
      name: day_blueprint_uuid
      in: path
      required: true
      description: "The UUID of the day blueprint"
      schema:
        $ref: "#/components/schemas/dayBlueprintUUID"

    mediaUUID:
      name: media_uuid
      in: path
      required: true
      description: "The UUID of the media resource"
      schema:
        $ref: "#/components/schemas/mediaUUID"

    taskBlueprintUUID:
      name: task_blueprint_uuid
      in: path
      required: true
      description: "The UUID of the task blueprint"
      schema:
        $ref: "#/components/schemas/taskBlueprintUUID"

    formBlueprintUUID:
      name: form_blueprint_uuid
      in: path
      required: true
      description: "The UUID of the form blueprint"
      schema:
        $ref: "#/components/schemas/formBlueprintUUID"

    fieldUUID:
      name: field_uuid
      in: path
      required: true
      description: "The UUID of the form field"
      schema:
        $ref: "#/components/schemas/fieldUUID"

    userUUID:
      name: user_uuid
      in: path
      required: true
      description: "The UUID of the user"
      schema:
        $ref: "#/components/schemas/userUUID"

  ######################################################
  # SCHEMAS
  ######################################################
  schemas:
    projectBlueprintUUID:
      type: string
      format: uuid
      pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
      description: "UUID for a Project Blueprint"

    dayBlueprintUUID:
      type: string
      format: uuid
      pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
      description: "UUID for a Day Blueprint"

    componentUUID:
      type: string
      format: uuid
      pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
      description: "UUID for a Day Component"

    taskBlueprintUUID:
      type: string
      format: uuid
      pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
      description: "UUID for a Task Blueprint"

    formBlueprintUUID:
      type: string
      format: uuid
      pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
      description: "UUID for a Form Blueprint"

    fieldUUID:
      type: string
      format: uuid
      pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
      description: "UUID for a Form Field"

    mediaUUID:
      type: string
      format: uuid
      pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
      description: "UUID for a Media resource"

    userUUID:
      type: string
      format: uuid
      pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
      description: "UUID for a User"

    sortOrder:
      type: integer
      description: "Order or position within a list"

    Error:
      type: object
      description: Error object
      example:
        message: "Error message"
      properties:
        message:
          type: string
          description: Error message
      required:
        - message

    ######################################################
    # Composite ID Schemas
    ######################################################
    ProjectDaysMapperId:
      type: object
      description: "Composite ID for ProjectDaysMapper"
      example:
        project_blueprint: "665c599d-5c8d-4d20-aaab-7ffaba150606"
        day: "557c482c-8bb5-4a65-9bef-848a953238ae"
      properties:
        project_blueprint_uuid:
          $ref: '#/components/schemas/projectBlueprintUUID'
        day_blueprint_uuid:
          $ref: '#/components/schemas/dayBlueprintUUID'
      required:
        - project_blueprint_uuid
        - day_blueprint_uuid

    ProjectInstanceId:
      type: object
      description: "Composite ID for ProjectInstance"
      example:
        project_blueprint_uuid: "665c599d-5c8d-4d20-aaab-7ffaba150606"
        user_uuid: "66de88ad-5c8d-4d20-a0ab-bbb7ccc15333"
      properties:
        project_blueprint_uuid:
          $ref: '#/components/schemas/projectBlueprintUUID'
        user_uuid:
          $ref: '#/components/schemas/userUUID'
      required:
        - project_blueprint_uuid
        - user_uuid

    FinancesId:
      type: object
      description: "Composite ID for Finances"
      example:
        project_blueprint_uuid: "665c599d-5c8d-4d20-aaab-7ffaba150606"
        user_uuid: "66de88ad-5c8d-4d20-a0ab-bbb7ccc15333"
      properties:
        project_blueprint_uuid:
          $ref: '#/components/schemas/projectBlueprintUUID'
        user_uuid:
          $ref: '#/components/schemas/userUUID'
      required:
        - project_blueprint_uuid
        - user_uuid

    MembersId:
      type: object
      description: "Composite ID for Members"
      example:
        project_blueprint_uuid: "665c599d-5c8d-4d20-aaab-7ffaba150606"
        user_uuid: "66de88ad-5c8d-4d20-a0ab-bbb7ccc15333"
      properties:
        project_blueprint_uuid:
          $ref: '#/components/schemas/projectBlueprintUUID'
        user_uuid:
          $ref: '#/components/schemas/userUUID'
      required:
        - project_blueprint_uuid
        - user_uuid

    DayComponentsMapperId:
      type: object
      description: "Composite ID for DayComponentsMapper"
      example:
        day_blueprint_uuid: "665c599d-5c8d-4d20-aaab-7ffaba150606"
        component_uuid: "a8494f64-0987-4dd0-8405-df19eb58f2ab"
      properties:
        day_blueprint_uuid:
          $ref: '#/components/schemas/dayBlueprintUUID'
        component_uuid:
          $ref: '#/components/schemas/componentUUID'
      required:
        - day_blueprint_uuid
        - component_uuid

    DayInstanceId:
      type: object
      description: "Composite ID for DayInstance"
      example:
        day_blueprint_uuid: "665c599d-5c8d-4d20-aaab-7ffaba150606"
        user_uuid: "66de88ad-5c8d-4d20-a0ab-bbb7ccc15333"
      properties:
        day_blueprint_uuid:
          $ref: '#/components/schemas/dayBlueprintUUID'
        user_uuid:
          $ref: '#/components/schemas/userUUID'
      required:
        - day_blueprint_uuid
        - user_uuid

    TaskInstanceId:
      type: object
      description: "Composite ID for TaskInstance"
      example:
        task_blueprint_uuid: "665c599d-5c8d-4d20-aaab-7ffaba150606"
        user_uuid: "66de88ad-5c8d-4d20-a0ab-bbb7ccc15333"
      properties:
        task_blueprint_uuid:
          $ref: '#/components/schemas/taskBlueprintUUID'
        user_uuid:
          $ref: '#/components/schemas/userUUID'
      required:
        - task_blueprint_uuid
        - user_uuid

    FormFieldMapperId:
      type: object
      description: "Composite ID for FormFieldMapper"
      example:
        form_blueprint_uuid: "665c599d-5c8d-4d20-aaab-7ffaba150606"
        field_uuid: "a8494f64-0987-4dd0-8405-df19eb58f2ab"
      properties:
        form_blueprint_uuid:
          $ref: '#/components/schemas/formBlueprintUUID'
        field_uuid:
          $ref: '#/components/schemas/fieldUUID'
      required:
        - form_blueprint_uuid
        - field_uuid

    FormInstanceId:
      type: object
      description: "Composite ID for FormInstance"
      example:
        form_blueprint_uuid: "665c599d-5c8d-4d20-aaab-7ffaba150606"
        user_uuid: "66de88ad-5c8d-4d20-a0ab-bbb7ccc15333"
      properties:
        form_blueprint_uuid:
          $ref: '#/components/schemas/formBlueprintUUID'
        user_uuid:
          $ref: '#/components/schemas/userUUID'
      required:
        - form_blueprint_uuid
        - user_uuid

    ######################################################
    # PROJECT
    ######################################################
    ProjectBlueprint:
      type: object
      properties:
        project_blueprint_uuid:
          $ref: '#/components/schemas/projectBlueprintUUID'
        poster_url:
          type: string
          description: "URL for the project poster image"
        welcome_video_url:
          type: string
          description: "URL for the project introduction video"
        title:
          type: string
        description:
          type: string
        difficulty:
          type: string
          enum:
            - "EASY"
            - "MEDIUM"
            - "HARD"
        style:
          type: string
          enum:
            - "DIY"
            - "READY-MADE"
      required:
        - project_blueprint_uuid
        - title

    ProjectDaysMapper:
      type: object
      description: "Entity for mapping days within a project"
      example:
        id:
          project_blueprint_uuid: "665c599d-5c8d-4d20-aaab-7ffaba150606"
          day_blueprint_uuid: "557c482c-8bb5-4a65-9bef-848a953238ae"
        sortOrder: 1
      properties:
        id:
          $ref: '#/components/schemas/ProjectDaysMapperId'
          readOnly: true
        sortOrder:
          $ref: '#/components/schemas/sortOrder'
      required:
        - id
        - sortOrder

    ProjectInstance:
      type: object
      description: "Entity for a user's specific project instance"
      example:
        id:
          project_blueprint_uuid: "665c599d-5c8d-4d20-aaab-7ffaba150606"
          user_uuid: "66de88ad-5c8d-4d20-a0ab-bbb7ccc15333"
        status: "IN_PROGRESS"
        start_date: "2021-09-01T10:00:00Z"
      properties:
        id:
          $ref: '#/components/schemas/ProjectInstanceId'
          readOnly: true
        status:
          type: string
          enum:
            - "IN_PROGRESS"
            - "COMPLETED"
        start_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time
        feedback:
          type: string
        what_went_well:
          type: string
      required:
        - id
        - status

    Finances:
      type: object
      description: "Entity for user finances on a specific project"
      example:
        id:
          project_blueprint_uuid: "665c599d-5c8d-4d20-aaab-7ffaba150606"
          user_uuid: "66de88ad-5c8d-4d20-a0ab-bbb7ccc15333"
        investor_gave: 100.0
        investor_return: 120.0
      properties:
        id:
          $ref: '#/components/schemas/FinancesId'
          readOnly: true
        investor_gave:
          type: number
          format: float
        investor_return:
          type: number
          format: float
        spent_budget:
          type: number
          format: float
        toys_planned:
          type: number
          format: float
        toys_sold:
          type: number
          format: float
        toys_left:
          type: number
          format: float
        members_budget:
          type: number
          format: float
        profit:
          type: number
          format: float
        expense_amount:
          type: number
          format: float
        calculated_budget:
          type: number
          format: float
        items_cost:
          type: number
          format: float
        recommended_price:
          type: number
          format: float
        price_per_item:
          type: number
          format: float
        sold_price:
          type: number
          format: float
      required:
        - id

    Members:
      type: object
      description: "Entity for user membership in a specific project"
      example:
        id:
          project_blueprint_uuid: "665c599d-5c8d-4d20-aaab-7ffaba150606"
          user_uuid: "66de88ad-5c8d-4d20-a0ab-bbb7ccc15333"
        member_name: "John Doe"
      properties:
        id:
          $ref: '#/components/schemas/MembersId'
          readOnly: true
        member_name:
          type: string
      required:
        - id
        - member_name

    ProjectDTO:
      type: object
      properties:
        blueprint:
          $ref: '#/components/schemas/ProjectBlueprint'
        instance:
          $ref: '#/components/schemas/ProjectInstance'
      required:
        - blueprint
        - instance

    ######################################################
    # DAY
    ######################################################
    DayBlueprint:
      type: object
      properties:
        day_blueprint_uuid:
          $ref: '#/components/schemas/dayBlueprintUUID'
        title:
          type: string
        description:
          type: string
        text:
          type: string
      required:
        - day_blueprint_uuid
        - title

    DayComponentsMapper:
      type: object
      description: "Mapping of components (tasks, forms, media) within a day"
      example:
        id:
          day_blueprint_uuid: "665c599d-5c8d-4d20-aaab-7ffaba150606"
          component_uuid: "a8494f64-0987-4dd0-8405-df19eb58f2ab"
        type: "TASK"
      properties:
        id:
          $ref: '#/components/schemas/DayComponentsMapperId'
          readOnly: true
        type:
          type: string
          enum:
            - "TASK"
            - "FORM"
            - "MEDIA"
      required:
        - id
        - type

    DayInstance:
      type: object
      description: "Specific instance of a day for a user"
      example:
        id:
          day_blueprint_uuid: "665c599d-5c8d-4d20-aaab-7ffaba150606"
          user_uuid: "66de88ad-5c8d-4d20-a0ab-bbb7ccc15333"
        status: "IN_PROGRESS"
      properties:
        id:
          $ref: '#/components/schemas/DayInstanceId'
          readOnly: true
        status:
          type: string
          enum:
            - "IN_PROGRESS"
            - "COMPLETED"
            - "NOT_STARTED"
      required:
        - id
        - status

    DayDTO:
      type: object
      properties:
        blueprint:
          $ref: '#/components/schemas/DayBlueprint'
        instance:
          $ref: '#/components/schemas/DayInstance'
      required:
        - blueprint
        - instance

    ######################################################
    # TASK
    ######################################################
    TaskBlueprint:
      type: object
      properties:
        task_blueprint_uuid:
          $ref: '#/components/schemas/taskBlueprintUUID'
        title:
          type: string
        description:
          type: string
      required:
        - task_blueprint_uuid
        - title

    TaskInstance:
      type: object
      description: "User's progress for a specific task"
      example:
        id:
          task_blueprint_uuid: "665c599d-5c8d-4d20-aaab-7ffaba150606"
          user_uuid: "66de88ad-5c8d-4d20-a0ab-bbb7ccc15333"
        status: true
      properties:
        id:
          $ref: '#/components/schemas/TaskInstanceId'
          readOnly: true
        status:
          type: boolean
          description: "True if completed, false otherwise"
      required:
        - id
        - status

    TaskDTO:
      type: object
      properties:
        blueprint:
          $ref: '#/components/schemas/TaskBlueprint'
        progress:
          $ref: '#/components/schemas/TaskInstance'
      required:
        - blueprint
        - progress

    ######################################################
    # FORM
    ######################################################
    FormBlueprint:
      type: object
      properties:
        form_blueprint_uuid:
          $ref: '#/components/schemas/formBlueprintUUID'
        title:
          type: string
        description:
          type: string
        callback_url:
          type: string
      required:
        - form_blueprint_uuid
        - title

    Field:
      type: object
      properties:
        field_uuid:
          $ref: '#/components/schemas/fieldUUID'
        input_type:
          type: string
          enum:
            - "TEXT"
            - "NUMBER"
            - "FILE"
        required:
          type: boolean
        title:
          type: string
        description:
          type: string
      required:
        - field_uuid
        - input_type
        - title

    FormFieldMapper:
      type: object
      description: "Mapping a field within a form"
      example:
        id:
          form_blueprint_uuid: "665c599d-5c8d-4d20-aaab-7ffaba150606"
          field_uuid: "a8494f64-0987-4dd0-8405-df19eb58f2ab"
        sortOrder: 1
      properties:
        id:
          $ref: '#/components/schemas/FormFieldMapperId'
          readOnly: true
        sortOrder:
          $ref: '#/components/schemas/sortOrder'
      required:
        - id
        - sortOrder

    FormInstance:
      type: object
      description: "Specific instance of a form for a user"
      example:
        id:
          form_blueprint_uuid: "665c599d-5c8d-4d20-aaab-7ffaba150606"
          user_uuid: "66de88ad-5c8d-4d20-a0ab-bbb7ccc15333"
        status: true
      properties:
        id:
          $ref: '#/components/schemas/FormInstanceId'
          readOnly: true
        status:
          type: boolean
          description: "True if form is completed, false otherwise"
      required:
        - id
        - status

    FormDTO:
      type: object
      properties:
        blueprint:
          $ref: '#/components/schemas/FormBlueprint'
        instance:
          $ref: '#/components/schemas/FormInstance'
      required:
        - blueprint
        - instance

    ######################################################
    # MEDIA
    ######################################################
    Media:
      type: object
      properties:
        mediaUUID:
          $ref: '#/components/schemas/mediaUUID'
        type:
          type: string
          enum:
            - "video"
            - "image"
        url:
          type: URI
          description: "URL for the media file"
        title:
          type: string
        description:
          type: string
      required:
        - mediaUUID
        - type
        - title

########################################################
# PATHS
########################################################
paths:

  ######################################################
  # SINGLE-ID RESOURCES (Blueprints, Media, etc.)
  ######################################################
  /projects:
    get:
      summary: List project blueprints
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
      responses:
        '200':
          description: A list of project blueprints
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectBlueprint'
    post:
      summary: Create new project blueprint (admin only)
      security:
        - admin_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectBlueprint'
      responses:
        '200':
          description: The created project blueprint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectBlueprint'

  /projects/{project_blueprint_uuid}:
    parameters:
      - $ref: '#/components/parameters/projectBlueprintUUID'
    get:
      summary: Get project blueprint details
      responses:
        '200':
          description: Project blueprint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectBlueprint'
    put:
      summary: Update an existing project blueprint (admin only)
      security:
        - admin_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectBlueprint'
      responses:
        '200':
          description: Updated project blueprint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectBlueprint'
    delete:
      summary: Delete a project blueprint (admin only)
      security:
        - admin_jwt: []
      responses:
        '204':
          description: No Content

  /days:
    get:
      summary: List day templates
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
      responses:
        '200':
          description: A list of day blueprints
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DayBlueprint'
    post:
      summary: Create day template (admin only)
      security:
        - admin_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DayBlueprint'
      responses:
        '200':
          description: Created day blueprint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DayBlueprint'

  /days/{day_blueprint_uuid}:
    parameters:
      - $ref: '#/components/parameters/dayBlueprintUUID'
    get:
      summary: Get day template details
      responses:
        '200':
          description: Day blueprint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DayBlueprint'
    put:
      summary: Update day template (admin only)
      security:
        - admin_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DayBlueprint'
      responses:
        '200':
          description: Updated day blueprint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DayBlueprint'
    delete:
      summary: Delete day template (admin only)
      security:
        - admin_jwt: []
      responses:
        '204':
          description: No Content

  /tasks:
    get:
      summary: List task templates
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
      responses:
        '200':
          description: A list of task templates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskBlueprint'
    post:
      summary: Create task template (admin only)
      security:
        - admin_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskBlueprint'
      responses:
        '200':
          description: Created task blueprint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskBlueprint'

  /tasks/{task_blueprint_uuid}:
    parameters:
      - $ref: '#/components/parameters/taskBlueprintUUID'
    get:
      summary: Get task template
      responses:
        '200':
          description: Task blueprint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskBlueprint'
    put:
      summary: Update task template (admin only)
      security:
        - admin_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskBlueprint'
      responses:
        '200':
          description: Updated task blueprint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskBlueprint'
    delete:
      summary: Delete task template (admin only)
      security:
        - admin_jwt: []
      responses:
        '204':
          description: No Content

  /forms:
    get:
      summary: List form templates
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
      responses:
        '200':
          description: A list of form templates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FormBlueprint'
    post:
      summary: Create form template (admin only)
      security:
        - admin_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormBlueprint'
      responses:
        '200':
          description: Created form blueprint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormBlueprint'

  /forms/{form_blueprint_uuid}:
    parameters:
      - $ref: '#/components/parameters/formBlueprintUUID'
    get:
      summary: Get form template
      responses:
        '200':
          description: Form blueprint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormBlueprint'
    put:
      summary: Update form template (admin only)
      security:
        - admin_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormBlueprint'
      responses:
        '200':
          description: Updated form blueprint
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormBlueprint'
    delete:
      summary: Delete form template (admin only)
      security:
        - admin_jwt: []
      responses:
        '204':
          description: No Content

  /media:
    post:
      summary: "Upload new media (admin only)"
      operationId: "mediaPostMultipart"
      security:
        - admin_jwt: [ ]
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: "The file to upload"
                description:
                  type: string
                  description: "Media description"
                type:
                  type: string
                  description: "Media type (e.g. video, image, etc.)"
              required:
                - file
        required: true
      responses:
        '200':
          description: "The uploaded media metadata"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Media"
    get:
      summary: (Optional) List media items
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
      responses:
        '200':
          description: A list of media
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Media'

  /media/{media_uuid}:
    parameters:
      - $ref: '#/components/parameters/mediaUUID'
    get:
      summary: Get media metadata
      responses:
        '200':
          description: Media metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Media'
    put:
      summary: Update media metadata (admin only)
      security:
        - admin_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Media'
      responses:
        '200':
          description: Updated media metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Media'
    delete:
      summary: Delete media (admin only)
      security:
        - admin_jwt: []
      responses:
        '204':
          description: No Content

  ######################################################
  # COMPOSITE-ID RESOURCES
  ######################################################

  ############################################
  # 1) PROJECT-DAYS-MAPPER
  ############################################
  /project-days-mapper:
    get:
      summary: List all project-day mappings
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
      responses:
        '200':
          description: A list of ProjectDaysMapper
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectDaysMapper'
    post:
      summary: Create a new project-day mapping (admin only)
      security:
        - admin_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectDaysMapper'
      responses:
        '200':
          description: Created project-day mapping
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDaysMapper'

  /project-days-mapper/{project_blueprint_uuid}/{day_blueprint_uuid}:
    parameters:
      - $ref: '#/components/parameters/projectBlueprintUUID'
      - $ref: '#/components/parameters/dayBlueprintUUID'
    get:
      summary: Get a specific project-day mapping
      responses:
        '200':
          description: A single ProjectDaysMapper
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDaysMapper'
    put:
      summary: Update a specific project-day mapping (admin only)
      security:
        - admin_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectDaysMapper'
      responses:
        '200':
          description: Updated mapping
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDaysMapper'
    delete:
      summary: Delete project-day mapping (admin only)
      security:
        - admin_jwt: []
      responses:
        '204':
          description: No Content

  ############################################
  # 2) DAY-COMPONENTS-MAPPER
  ############################################
  /day-components-mapper:
    get:
      summary: List all day-component mappings
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
      responses:
        '200':
          description: A list of DayComponentsMapper
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DayComponentsMapper'
    post:
      summary: Create a new day-component mapping (admin only)
      security:
        - admin_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DayComponentsMapper'
      responses:
        '200':
          description: Created day-component mapping
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DayComponentsMapper'

  /day-components-mapper/{day_blueprint_uuid}/{component_uuid}:
    parameters:
      - $ref: '#/components/parameters/dayBlueprintUUID'
      - $ref: '#/components/parameters/componentUUID'
    get:
      summary: Get a specific day-component mapping
      responses:
        '200':
          description: DayComponentsMapper
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DayComponentsMapper'
    put:
      summary: Update a day-component mapping (admin only)
      security:
        - admin_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DayComponentsMapper'
      responses:
        '200':
          description: Updated mapping
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DayComponentsMapper'
    delete:
      summary: Delete day-component mapping (admin only)
      security:
        - admin_jwt: []
      responses:
        '204':
          description: No Content

  ############################################
  # 3) PROJECT-INSTANCES
  ############################################
  /project-instances:
    get:
      summary: List all project instances
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/userUUID'
      security:
        - user_jwt: []
      responses:
        '200':
          description: A list of ProjectInstance
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectDTO'
    post:
      summary: Create a new project instance (user)
      security:
        - user_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectInstance'
      responses:
        '200':
          description: Created project instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDTO'

  /project-instances/{project_blueprint_uuid}/{user_uuid}:
    parameters:
      - $ref: '#/components/parameters/projectBlueprintUUID'
      - $ref: '#/components/parameters/userUUID'
    get:
      summary: Get a specific project instance
      security:
        - user_jwt: []
      responses:
        '200':
          description: ProjectInstance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDTO'
    put:
      summary: Update a project instance (user)
      security:
        - user_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectInstance'
      responses:
        '200':
          description: Updated project instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDTO'
    delete:
      summary: Delete a project instance (admin or user)
      # Decide on your actual policy
      security:
        - admin_jwt: []
      responses:
        '204':
          description: No Content

  ############################################
  # 4) FINANCES
  ############################################
  /finances:
    get:
      summary: List all finances records
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
      security:
        - user_jwt: []
      responses:
        '200':
          description: A list of Finances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Finances'
    post:
      summary: Create new finances record
      security:
        - user_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Finances'
      responses:
        '200':
          description: Created finances
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Finances'

  /finances/{project_blueprint_uuid}/{user_uuid}:
    parameters:
      - $ref: '#/components/parameters/projectBlueprintUUID'
      - $ref: '#/components/parameters/userUUID'
    get:
      summary: Get finances record
      security:
        - user_jwt: []
      responses:
        '200':
          description: Finances
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Finances'
    put:
      summary: Update finances record
      security:
        - user_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Finances'
      responses:
        '200':
          description: Updated finances
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Finances'
    delete:
      summary: Delete finances record
      security:
        - user_jwt: []
      responses:
        '204':
          description: No Content

  # Example sub-path to "calculate" finances:
  /finances/{project_blueprint_uuid}/{user_uuid}/calculate:
    parameters:
      - $ref: '#/components/parameters/projectBlueprintUUID'
      - $ref: '#/components/parameters/userUUID'
    put:
      summary: Calculate or recalculate finances
      security:
        - user_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Finances'
      responses:
        '200':
          description: Calculated finances
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Finances'

  ############################################
  # 5) MEMBERS
  ############################################
  /members:
    get:
      summary: List all members records
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
      security:
        - user_jwt: []
      responses:
        '200':
          description: A list of Members
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Members'
    post:
      summary: Create new members record
      security:
        - user_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Members'
      responses:
        '200':
          description: Created members record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Members'

  /members/{project_blueprint_uuid}/{user_uuid}:
    parameters:
      - $ref: '#/components/parameters/projectBlueprintUUID'
      - $ref: '#/components/parameters/userUUID'
    get:
      summary: Get one member record
      security:
        - user_jwt: []
      responses:
        '200':
          description: Members
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Members'
    put:
      summary: Update a member record
      security:
        - user_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Members'
      responses:
        '200':
          description: Updated member
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Members'
    delete:
      summary: Delete a member record
      security:
        - user_jwt: []
      responses:
        '204':
          description: No Content

  ############################################
  # 6) DAY-INSTANCES
  ############################################
  /day-instances:
    get:
      summary: List all day instances
      parameters:
        - $ref: '#/components/parameters/userUUID'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
      security:
        - user_jwt: []
      responses:
        '200':
          description: A list of DayInstance
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DayDTO'
    post:
      summary: Create a day instance
      security:
        - user_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DayInstance'
      responses:
        '200':
          description: Created day instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DayDTO'

  /day-instances/{day_blueprint_uuid}/{user_uuid}:
    parameters:
      - $ref: '#/components/parameters/dayBlueprintUUID'
      - $ref: '#/components/parameters/userUUID'
    get:
      summary: Get a specific day instance
      security:
        - user_jwt: []
      responses:
        '200':
          description: DayInstance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DayDTO'
    put:
      summary: Update a day instance
      security:
        - user_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DayInstance'
      responses:
        '200':
          description: Updated day instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DayDTO'
    delete:
      summary: Delete a day instance
      security:
        - user_jwt: []
      responses:
        '204':
          description: No Content

  ############################################
  # 7) TASK-INSTANCES
  ############################################
  /task-instances:
    get:
      summary: List all task instances
      parameters:
        - $ref: '#/components/parameters/userUUID'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
      security:
        - user_jwt: []
      responses:
        '200':
          description: A list of TaskInstance
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskDTO'
    post:
      summary: Create a new task instance
      security:
        - user_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInstance'
      responses:
        '200':
          description: Created task instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDTO'

  /task-instances/{task_blueprint_uuid}/{user_uuid}:
    parameters:
      - $ref: '#/components/parameters/taskBlueprintUUID'
      - $ref: '#/components/parameters/userUUID'
    get:
      summary: Get a user's specific task instance
      security:
        - user_jwt: []
      responses:
        '200':
          description: TaskInstance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDTO'
    put:
      summary: Update a task instance
      security:
        - user_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInstance'
      responses:
        '200':
          description: Updated task instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDTO'
    delete:
      summary: Delete a task instance
      security:
        - user_jwt: []
      responses:
        '204':
          description: No Content

  ############################################
  # 8) FORM-FIELD-MAPPER
  ############################################
  /form-field-mapper:
    get:
      summary: List all form-field mappings
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/userUUID'
      security:
        - admin_jwt: []
      responses:
        '200':
          description: A list of FormFieldMapper
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FormFieldMapper'
    post:
      summary: Create a form-field mapping (admin only)
      security:
        - admin_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormFieldMapper'
      responses:
        '200':
          description: Created form-field mapping
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormFieldMapper'

  /form-field-mapper/{form_blueprint_uuid}/{field_uuid}:
    parameters:
      - $ref: '#/components/parameters/formBlueprintUUID'
      - $ref: '#/components/parameters/fieldUUID'
    get:
      summary: Get a specific form-field mapping
      security:
        - admin_jwt: []
      responses:
        '200':
          description: A single FormFieldMapper
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormFieldMapper'
    put:
      summary: Update a form-field mapping (admin only)
      security:
        - admin_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormFieldMapper'
      responses:
        '200':
          description: Updated form-field mapping
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormFieldMapper'
    delete:
      summary: Delete a form-field mapping (admin only)
      security:
        - admin_jwt: []
      responses:
        '204':
          description: No Content

  ############################################
  # 9) FORM-INSTANCES
  ############################################
  /form-instances:
    get:
      summary: List all form instances
      parameters:
        - $ref: '#/components/parameters/userUUID'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
      security:
        - user_jwt: []
      responses:
        '200':
          description: A list of FormInstance
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FormDTO'
    post:
      summary: Create a form instance (user)
      security:
        - user_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormInstance'
      responses:
        '200':
          description: Created form instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormDTO'

  /form-instances/{form_blueprint_uuid}/{user_uuid}:
    parameters:
      - $ref: '#/components/parameters/formBlueprintUUID'
      - $ref: '#/components/parameters/userUUID'
    get:
      summary: Get a user's specific form instance
      security:
        - user_jwt: []
      responses:
        '200':
          description: FormInstance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormDTO'
    put:
      summary: Update a form instance
      security:
        - user_jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormInstance'
      responses:
        '200':
          description: Updated form instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormDTO'
    delete:
      summary: Delete a form instance
      security:
        - user_jwt: []
      responses:
        '204':
          description: No Content
